### ISSUE TITLE
Create a method that will fetch the data from the API link

### ISSUE THREAD

**Issue by infiniteoverflow** [bellatrixdatacommunity/Covid19-Tracker-App#2]
The API link has been provided in the README.md file.

**Comment by swatiprajapati08** [comment]
Can u assign this issue to me?

**Comment by infiniteoverflow** [comment]
sure :) Go ahead !!

**Comment by infiniteoverflow** [comment]
Make sure u store all the necessary data in corresponding variables , and log output to see if its working perfectly

**Comment by swatiprajapati08** [comment]
It is fetching the data correctly. I had displayed it on screen. Please review it.

**Comment by infiniteoverflow** [comment]
Can u make a PR for the change , i cant review it without that.
