### ISSUE TITLE
Modify the README.md file

### ISSUE THREAD

**Issue by infiniteoverflow** [bellatrixdatacommunity/Covid19-Tracker-App#5]

**Comment by ojasvikhurana** [comment]
What needs to be modified in it?

**Comment by infiniteoverflow** [comment]
I will be sharing some mock ui for the app in the slack channel , you can add that in the README.md file after that :)

**Comment by ojasvikhurana** [comment]
can you assign me this issue?

**Comment by infiniteoverflow** [comment]
sure , go ahead
